export const SAVEUSERINFO = "saveuserinfo"
export const LOGOUT = "logout"
export const GETSHOPGOODS = "getshopgoods"
export const GETCOMMENTS = "getcomments"
export const GETHEADER = "getheader"
export const ADDFOOD = "addfood"
export const CLEARCART = "clearcart"
